### PR TITLE
Allow to set more than one hosted domain

### PR DESCRIPTION
**Pull request by michal-kazmierczak**
Changes:
- allow more than one hd (Hosted Domain)
- added tests for this case
- updated README

This is very helpful when your app needs to support several hosted domains.

### CODE REVIEW

**Comment by zquestz** [comment]
Looks good, mind squashing your commits before merge?

**Comment by michal-kazmierczak** [comment]
No problem, feel free to do this.

**Comment by zquestz** [comment]
I can't squash commits in your repo. That is something you have to do. Once that is complete I am happy to merge.

**Comment by michal-kazmierczak** [comment]
Yeah, sorry for an oversight. It's done. 
Thanks.

**Comment by micred** [comment]
Excuse me guys, can you provide help to this issue: https://github.com/lynndylanhurley/devise_token_auth/issues/898 ?

Thank you very much.

**Pull request merged**
