### PR TITLE
follow jwt 2.9.0 changes

### PR DESCRIPTION
**Pull request by nov**
fixes https://github.com/zquestz/omniauth-google-oauth2/issues/463

* `JWT::Verify.verify_claims` -> `JWT::Claims.verify!`
* enforce JWT 2.9.0+

### CODE REVIEW

**Comment by zquestz** [comment]
Don't mind this change, but we will need to bump a minor version and cut this as version 1.2.

This bumps our Ruby dependency from >= 2.2 to >= 2.5.

Many people who use this software will not be able to do this change.

That being said, keeping current is important. =)

**Comment by nov** [comment]
do you want me to update the version too?

**Comment by nov** [comment]
OK, updated gem & ruby versions.

**Comment by zquestz** [comment]
This looks legit, lets merge and I will focus on any other minor changes and push a release. =)

**Comment by zquestz** [comment]
New release is out. =)

**Pull request merged**
