### PR TITLE
Use the `People: get` endpoint for `raw_info` hash

### PR DESCRIPTION
**Pull request by gf3**
* Discussion → https://github.com/zquestz/omniauth-google-oauth2/pull/147

### CODE REVIEW

**Comment by DmitrySharikov** [comment]
@zquestz Hello! Can you explain why adding additional call with [url like this](https://github.com/DmitrySharikov/omniauth-google-oauth2/blob/master/lib/omniauth/strategies/google_oauth2.rb#L84) breaks the test?

**Comment by zquestz** [comment]
I can look at it a bit tonight. See if we can figure something out with this PR. Been around for too long.

**Comment by westonhankins** [comment]
Any update on this? It would also be useful to us.

**Comment by zquestz** [comment]
So I think I am going to stick with my openid endpoint. However I think this could be useful as a README example in the success callback. Then people can fetch the additional metadata if they need it, and we don't hit the G+ endpoint.

**Pull request closed without merging**
