### PR TITLE
Fix Redirect Uri

### PR DESCRIPTION
**Pull request by matiassalles99**
- When passing redirect url via query param & code or access token via body the redirect url was not being overriden
- Allow redirect url also via body

### CODE REVIEW

**Comment by matiassalles99** [comment]
Screen Shot 2021-11-10 at 18 17 21

Travis CI failing for unrelated reason

**Review by zquestz — APPROVED** [review]

**Comment by zquestz** [comment]
If you can add a test that would be epic.

**Comment by matiassalles99** [comment]
Will do so!

**Comment by matiassalles99** [comment]
@zquestz Just added the test, please let me know if its okay or you have any improvements/suggestions of this or another test to do before merging

**Comment by matiassalles99** [comment]
Also, this pr might close this issue [#391](https://github.com/zquestz/omniauth-google-oauth2/issues/391), in case you want to check it out

**Review by zquestz — APPROVED** [review]

**Pull request merged**
